local ng = require("neogen")
local map = vim.keymap.set

map("n", "<leader>gd", function()
	ng.generate({ type = "any" })
end, { desc = "Generate Matching Annotations" })
map("n", "<leader>gf", function()
	ng.generate({ type = "func" })
end, { desc = "Generate Function Annotations" })
map("n", "<leader>gF", function()
	ng.generate({ type = "file" })
end, { desc = "Generate File Annotations" })
map("n", "<leader>gc", function()
	ng.generate({ type = "class" })
end, { desc = "Generate Class Annotations" })
map("n", "<leader>gt", function()
	ng.generate({ type = "type" })
end, { desc = "Generate Type Annotations" })
