local map = vim.keymap.set

map("n", "<F5>", function()
	require("dap").continue()
end, { desc = "DAP Continue" })
map("n", "<F10>", function()
	require("dap").step_over()
end, { desc = "DAP Step Over" })
map("n", "<F11>", function()
	require("dap").step_into()
end, { desc = "DAP Step Into" })
map("n", "<F12>", function()
	require("dap").step_out()
end, { desc = "DAP Step Out" })
map("n", "<leader>bb", function()
	require("dap").toggle_breakpoint()
end, { desc = "DAP Toggle Breakpoint" })
map("n", "<leader>bB", function()
	require("dap").set_breakpoint()
end, { desc = "DAP Set Breakpoint" })
map("n", "<leader>lp", function()
	require("dap").set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end, { desc = "DAP Log Point Message" })
map("n", "<leader>dr", function()
	require("dap").repl.open()
end, { desc = "DAP REPL Open" })
map("n", "<leader>dl", function()
	require("dap").run_last()
end, { desc = "DAP Run Last" })
map({ "n", "v" }, "<leader>dh", function()
	require("dap.ui.widgets").hover()
end, { desc = "DAP Hover" })
map({ "n", "v" }, "<leader>dp", function()
	require("dap.ui.widgets").preview()
end, { desc = "DAP Preview" })
map("n", "<leader>df", function()
	local widgets = require("dap.ui.widgets")
	widgets.centered_float(widgets.frames)
end, { desc = "DAP Inspect Frame" })
map("n", "<leader>ds", function()
	local widgets = require("dap.ui.widgets")
	widgets.centered_float(widgets.scopes)
end, { desc = "DAP Inspect Scope" })
